version: '3.8'

services:
  openinterpreter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      # Add other necessary environment variables like API keys here
      # Example: OPENAI_API_KEY: your_openai_api_key
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - openinterpreter_network

networks:
  openinterpreter_network:
    driver: bridge
